services:
  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./fastapi:/app
    environment:
      - DATABASE_URL=mysql+pymysql://root:example@db:3306/mydatabase
    working_dir: /app
    command: "uvicorn main:app --reload --host 0.0.0.0 --port 8080"
    depends_on:
      - db
  
  streamlit:
    build:
      context: ./streamlit
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit:/app
    environment:
      - API_URL=http://192.168.1.3:8080/recommendations/
    working_dir: /app
    command: "streamlit run app.py"
    depends_on:
      - db
      - fastapi
    
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=mydatabase
      - DATABASE_URL=mysql+pymysql://root:example@db:3306/mydatabase
    volumes:
      - ./mysql/data:/data
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - mysql-local:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d

volumes:
  mysql-local:
